spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: 1
      password: 1
  mvc:
    view:
      prefix: /
      suffix: .jsp
